apiVersion: apps/v1
kind: Deployment
metadata:
  name: brewbook
  labels:
    app: brewbook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brewbook
  template:
    metadata:
      labels:
        app: brewbook
    spec:
      containers:
      - name: brewbook
        image: Huu_Truc_Nguyen/brewbook:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: brewbook-secrets
              key: supabase-url
        - name: NEXT_PUBLIC_SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: brewbook-secrets
              key: supabase-anon-key
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        imagePullPolicy: Always
